### ISSUE TITLE
How check flx fuzzy matching is working?

### ISSUE THREAD

**Issue by ReneFroger** [PythonNut/helm-flx#2]
Thanks for sharing this package! 

Is there any way to check if flx fuzzy matching is working inside Helm, that Helm doesn't use his own fuzzy mechanism?

**Comment by PythonNut** [comment]
Good question. For a long time,  I just assumed that it was working,  only to discover that my code was never invoked for `helm-find-files`. It turns out the sorting method there can't be changed. 

The method I use now is to check if something short like `plp` correctly brings `package-list-packages` to the top in `helm-M-x`. Pretty unscientific, but it seems to serve me well in practice.

**Comment by AlKapote** [comment]
Add a `(debug)` to the start of `helm-flx-fuzzy-matching-sort` then bring up a helm buffer and try to match something: If the debug fires - it's working.

**Comment by PythonNut** [comment]
Well, if you want to be nuclear, you can do <kbd>M-x</kbd> `debug-on-entry` <kbd>RET</kbd> `helm-flx-fuzzy-matching-sort` <kbd>RET</kbd>, which should be easier than modifying the source.

**Comment by ReneFroger** [comment]
After following your instructions, I started `helm-M-x`, but I got a bug backtrace buffer with debugger, entering a function `helm-flx-fuzzy-matching-sort`. So I assume there is fuzzy matching from `flx` for `helm-or-files`, and not the fuzzy matching from Helm inside?

**Comment by PythonNut** [comment]
Yes, that is correct.

**Comment by ReneFroger** [comment]
Then `flx` is active inside `helm-for-files` :smile:. Thanks for your reply.
